# Generated by Django 5.1.3 on 2024-12-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='ready_for_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
