# Generated by Django 5.1.3 on 2025-01-03 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_rename_shoppingcart_shoppingcartmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='menu_items',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='category',
            name='merchant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Merchant'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='customer.profile'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='merchant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Merchant'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='customer.profile'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='customer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Customer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_cust', to='customer.profile'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='merchant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Merchant'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customer.profile'),
        ),
    ]
