# Generated by Django 5.1.3 on 2025-01-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_profile_init_menu_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='init_menu_items',
        ),
    ]
