# Generated by Django 5.1.3 on 2025-01-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_remove_profile_init_menu_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Preparationp', 'Under Preparation'), ('Ready for Pickup', 'Ready for Pickup'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
