# Generated by Django 5.1.3 on 2025-01-12 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Notification message', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, help_text='Associated order for the notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customer.ordermodel')),
                ('recipient', models.ForeignKey(help_text='The user receiving the notification', on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='customer.profile')),
                ('sender', models.ForeignKey(help_text='The user sending the notification', on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='customer.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
