# Generated by Django 5.1.3 on 2025-01-12 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_message_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='The driver assigned to deliver this order', limit_choices_to={'role': 'Driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_driver', to='customer.profile'),
        ),
    ]
