# Generated by Django 5.1.3 on 2025-01-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_ordermodel_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Preparationp', 'Under Preparation'), ('Ready for Pickup', 'Ready for Pickup'), ('Order On the Way', 'Order On the Way'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
