# Generated by Django 5.1.3 on 2025-01-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='requires_action',
            field=models.BooleanField(default=False, help_text='Does this message require recipient action?'),
        ),
    ]
