# Generated by Django 5.1.3 on 2025-01-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_message_requires_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='rating',
            field=models.PositiveIntegerField(blank=True, help_text='Rating given by the customer (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='rating_comment',
            field=models.TextField(blank=True, help_text='Optional comment for the rating', null=True),
        ),
    ]
