# Generated by Django 5.1.3 on 2025-01-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_ordermodel_rating_ordermodel_rating_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Time when the order was marked as delivered', null=True),
        ),
    ]
